a = input("Enter a number: ")
b = input("Enter another number: ")
sum = a+b
print('\nData type sum: ', sum ,type(sum))
sum = int(a)+int(b)
print('\nData type sum: ', sum ,type(sum))
sum =float(a) + float(b)
print('\nData type sum: ', sum ,type(sum))
sum = chr(int(sum))
print('\nData type sum: ', sum ,type(sum))
